---
title: "CDS 101 – Final Project Proposal"
author: "Team 3: Athir, Lorenzo, Abel"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    css: "gmu-cds101.css"
    toc: true
    toc_depth: 3
    number_sections: true
  pdf_document:
    toc: true
---

## 1. Dataset

**DC Metro Crime Data**  
**Kaggle**  

**Short Description:**  

This is a DC Metro Crime Dataset that contains records of crimes in the Washington DC Metropolitan area from December 31st, 2007, to November 2nd, 2017. This dataset provides an extremely rich source for analyzing crime patterns and determining key trends. This dataset is relevant to our purpose of identifying burglary patterns, as it includes a variety of variables like offense, shift, block, district, etc. For our project, we will use the two key variables, offense and shift, to determine the time of day burglaries have occurred. 

---

## 2. Dataset Link

` https://www.kaggle.com/datasets/vinchinzu/dc-metro-crime-data`

---

## 3. Research Question


> _Does the frequency of burglary incidents in the DC Metro area differ across different times of the day?_


---

## 4. Modeling Approach / Models Used

Describe what you plan to do analytically.

- Type of task (check all that apply):
  - [ ] Exploratory analysis only  
  - [ ] Regression (predicting a numeric value)  
  - [X] Classification (predicting categories/labels)  
  - [ ] Clustering / unsupervised patterns  
  - [ ] Other (describe)

**Planned models / methods:**

Method: The method we decided to use after discussing with each other, is hypothesis testing. We will be specifically targeting burglary as the type of offense and the shifts (time of day) will be the other variable we will be measuring. 

Null Hypothesis: There is no difference in the occurrence of burglary during any time of day (meaning there is no specific time of day where burglary is more common. 

Alternative hypothesis: There is a difference in the occurrence of burglary during a time of day (meaning a specific time of day has more burglaries occurring than the other times of day. In this case, we believe that during the night, there will be the most amount of burglaries being committed.) 


**Planned evaluation metrics:**

Examples:  
- Regression: RMSE, MAE, \(R^2\)  
- Classification: accuracy, precision/recall, F1, confusion matrix  

---

## 5. Expected Results

What do you expect to find? It’s okay if this changes later.

- Bullet point 1 (e.g., “We expect feature X to be a strong predictor of Y.”)  
- Bullet point 2  
- Bullet point 3  


---

**Submitted on:**  
11-23-2025
